os: linux
dist: focal  # or use other Ubuntu versions like xenial or bionic

stages:
  - name: init
  - name: maven_build
  - name: sonar_analysis
  - name: docker_build_and_push
  - name: deploy_to_eks

cache:
  directories:
    - target

jobs:
  include:
    - stage: init
      script:
        # Install necessary tools on Ubuntu
        - sudo apt-get update -y
        - sudo apt-get install -y openjdk-11-jdk maven docker.io awscli wget
        - sudo apt-get install -y apt-transport-https gnupg2 curl
        - sudo mkdir /ocp-tools
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-client-linux.tar.gz -P /ocp-tools
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-install-linux.tar.gz -P /ocp-tools
        - sudo ls -la /ocp-tools
        - cd ocp-tools
        - sudo chmod 777 *
        - sudo tar xvf openshift-install-linux.tar.gz openshift-install
        - sudo tar xvf openshift-client-linux.tar.gz oc kubectl
        - sudo cp oc kubectl /usr/local/bin
        - sudo oc version
        - sudo kubectl version
        - aws --version

    - stage: maven_build
      script:
        - mvn clean package
        - mv /home/travis/build/MSREEHARI17/demo_sample_apps/target/ $HOME/target-cache/

    - stage: sonar_analysis
      script:
        - mvn clean install sonar:sonar -Dsonar.organization=sreekantreddy -Dsonar.projectKey=sreekantreddy_travis-ci -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c64e9ce0ba777d04bedf1834303122c93faf6ad3
        
    - stage: docker_build_and_push
      script:
        - docker build -t cloudzenix/travis-ci .
        - docker login -u cloudzenix -p Cloudzenix@456
        - docker push cloudzenix/travis-ci

    - stage: deploy_to_eks
      script:
        # Run EKS deployment commands here
        - kubectl apply -f eks-deployment.yaml
