os: linux
dist: focal  # or use other Ubuntu versions like xenial or bionic

stages:

  - name: deploy_to_eks


jobs:
  include:
    - stage: init
      script:
        - sudo apt-get install -y awscli wget
    - stage: deploy_to_eks
      script:
        # Run EKS deployment commands here
        - sudo mkdir /ocp-tools
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-client-linux.tar.gz -P /ocp-tools
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-install-linux.tar.gz -P /ocp-tools
        - sudo ls -la /ocp-tools
        - pwd
        - sudo chmod 777 /ocp-tools/*
        - sudo tar xvf /ocp-tools/openshift-install-linux.tar.gz openshift-install
        - sudo tar xvf /ocp-tools/openshift-client-linux.tar.gz oc kubectl
        - sudo cp kubectl /usr/local/bin
        - sudo kubectl version
        - pwd
        - ls -la
        - aws configure set aws_access_key_id AKIA6IWZ6G25Y7BA4WNY
        - aws configure set aws_secret_access_key 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
        - aws sts get-caller-identity
        - TEMP_CREDS_JSON=$(aws sts assume-role --role-arn arn:aws:iam::980783347387:role/AdminAccess --role-session-name SESSION_NAME --query 'Credentials' --output json)
        - aws configure set aws_access_key_id $(echo $TEMP_CREDS_JSON | jq -r '.AccessKeyId')
        - aws configure set aws_secret_access_key $(echo $TEMP_CREDS_JSON | jq -r '.SecretAccessKey')
        - aws configure set aws_session_token $(echo $TEMP_CREDS_JSON | jq -r '.SessionToken')
        - aws sts get-caller-identity
        - aws eks --region us-east-1 update-kubeconfig --name EKS-Cluster
        - sudo kubectl get nodes

