os: linux
dist: focal  # or use other Ubuntu versions like xenial or bionic

stages:
  - name: init
  - name: deploy_to_eks

cache:
  directories:
    - ocptools

jobs:
  include:
    - stage: init
      script:
        # Install necessary tools on Ubuntu
        - pwd
        - sudo apt-get update -y
        - sudo apt-get install -y wget
        - sudo mkdir -p /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - pwd 
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-client-linux.tar.gz -P /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - sudo wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.6/openshift-install-linux.tar.gz -P /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - sudo ls -la /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - cd /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - pwd
        - sudo chmod 777 *
        - sudo tar xvf openshift-install-linux.tar.gz openshift-install
        - sudo tar xvf openshift-client-linux.tar.gz oc kubectl
        - sudo mv /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools $HOME/ocptools-cache
        - sudo cp oc kubectl /usr/local/bin
        - sudo oc version
        - sudo kubectl version

    - stage: deploy_to_eks
      script:
        # Run EKS deployment commands here
        - sudo ls -la /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - cd /home/travis/build/MSREEHARI17/demo_sample_apps/ocptools
        - pwd
        - ls -la
        - sudo cp oc kubectl /usr/local/bin
        - sudo oc version
        - sudo kubectl version
        - sudo kubectl delete -f deployment.yaml --ignore-not-found=true
        - sudo kubectl apply -f deployment.yaml
        - sudo oc delete -f deployment.yaml --ignore-not-found=true
        - sudo oc apply -f deployment.yaml
